### ISSUE TITLE
Problems getting GHES to run on AWS EKS, etc when using emulation mode

### ISSUE THREAD

**Issue by willsmythe** [willsmythe/ghes-kubevirt#6]
## Summary

When "emulation mode" is enabled in KubeVirt, the GitHub Enterprise Server VM never gets into a good state (usually failing with messages about HAProxy but other services fail to start or time out as well).

## AWS EKS test

On a new AWS EKS cluster with `debug.useEmulation` not set, the GHES VMI fails during "scheduling" with an `Insufficient devices.kubevirt.io/kvm` error. Not too surprising.

Alternatively, when `debug.useEmulation` is set to `true`, the VM starts and is accessible via VNC, but shows errors about the HAProxy service timing out / failing to start (see discussion in #1).

Side note: I'm fairly sure AWS doesn't support KVM on EC2 with the exception of "metal" instances, but I was hoping C5 (and maybe M5) would based on the [EC2 FAQ](https://aws.amazon.com/ec2/faqs/):

> Q. What is the underlying hypervisor on C5 instances?
> C5 instances use a new EC2 hypervisor that is based on core KVM technology.

## Azure Kubernetes Service (AKS) test

The GHES VM **comes up and runs correctly** (without emulation) on AKS when using either the Ev3 or Dv3 node types (both of which [support nested virtualization](https://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/).

Before getting it to work, I tried a different node type and the VMI scheduling failed (Insufficient devices.kubevirt.io/kv). Turning on emulation and deploying allowed the VM to come up, but failed with the HAProxy, etc service problems.

## High-level steps 

See [README.md](https://github.com/willsmythe/ghes-kubevirt/blob/master/README.md]) for deploy steps, but essentially:

1. Create an AWS EKS cluster (Kubernetes version 1.12.x)
1. Deploy CDI
2. Deploy KubeVirt operator
3. Create configmap (without `debug.useEmulation`):
    ```
    kubectl create configmap kubevirt-config -n kubevirt --from-literal feature-gates=DataVolumes
    ``` 
4. Deploy KubeVirt CR
5. Deploy 2 "datavolumes" (referenced by the VM resource)
6. Deploy VM resource (which has `running: true`, so the VMI, etc are created)

## Example VMI resource

Here is one of the VMI resources that failed when emulation was not enabled and the underlying node didn't support virtualization:

```
Name:         ghes-vm
Namespace:    default
Labels:       kubevirt.io/vm=ghes-vm
Annotations:  <none>
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2019-06-13T00:34:46Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generate Name:  ghes-vm
  Generation:     1
  Owner References:
    API Version:           kubevirt.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  ghes-vm
    UID:                   0bc46231-8d73-11e9-bcec-02d5966b8f8e
  Resource Version:        4106
  Self Link:               /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/ghes-vm
  UID:                     0bc81710-8d73-11e9-bcec-02d5966b8f8e
Spec:
  Domain:
    Devices:
      Disks:
        Boot Order:  1
        Disk:
          Bus:       virtio
        Name:        root-disk
        Boot Order:  2
        Disk:
          Bus:  virtio
        Name:   data-disk
      Interfaces:
        Bridge:
        Name:  default
        Ports:
          Port:      8443
          Protocol:  TCP
          Port:      8080
          Protocol:  TCP
          Port:      122
          Protocol:  TCP
          Port:      1194
          Protocol:  UDP
          Port:      123
          Protocol:  UDP
          Port:      161
          Protocol:  UDP
          Port:      443
          Protocol:  TCP
          Port:      80
          Protocol:  TCP
          Port:      22
          Protocol:  TCP
          Port:      9418
          Protocol:  TCP
          Port:      25
          Protocol:  TCP
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  8898bbd3-dc5f-5ad5-a579-05ba6e06a6a6
    Machine:
      Type:  q35
    Resources:
      Limits:
        Cpu:     2
        Memory:  20Gi
      Requests:
        Cpu:     2
        Memory:  16Gi
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  0
  Volumes:
    Data Volume:
      Name:  ghes-root-dv
    Name:    root-disk
    Data Volume:
      Name:  ghes-data-dv
    Name:    data-disk
Status:
  Conditions:
    Last Probe Time:       2019-06-13T00:34:47Z
    Last Transition Time:  2019-06-13T00:34:47Z
    Message:               0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Phase:                   Scheduling
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  SuccessfulCreate  86s   virtualmachine-controller  Created virtual machine pod virt-launcher-ghes-vm-kxx4z
```

**Comment by willsmythe** [comment]
@davidvossel, @fabiand, @dcritch - thanks for your help already on getting the GitHub Enterprise Server application VM running via KubeVirt. 

* **Good news**: we have the **GHES VM up and running in Azure Kubernetes Service**. Azure has a few node types (i.e. VM SKUs) -- Ev3 or Dv3 --- that support nested virtualization so it was relatively fast and easy to get up and running. 

* **Bad news**: is that **we still can't get the GHES VM running in AWS EKS**. I initially tried standing up my own EC2 instance and managing the cluster myself, but I got stuck getting EBS storage configured. However, I think this EC2 instance would have eventually run into the same problem as AWS EKS (lack of KVM/nested virtualization, forcing me to enable emulation mode). See issue description for more details.

The main questions we have for you are ...

1. Do you know if anyone has successfully deployed VMs via KubeVirt in AWS EKS or EC2 without enabling emulation?

2. Do you have any other ideas on why enabling emulation causes services (e.g. HAProxy) to fail to start in the VM? I initially assumed it was a network problem (and it might still be), but I also wonder if emulation mode is causing such a perf impact that services simply can't start in a reasonable amount of time.

Thanks again for any additional thoughts. We're almost there ...

**Comment by willsmythe** [comment]
@mariorod - FYI

**Comment by davidvossel** [comment]
hey,

> The GHES VM comes up and runs correctly (without emulation) on AKS when using either the Ev3 or Dv3 node types (both of which support nested virtualization.

Excellent to hear! Did you all by any chance test GKE with nested virtualization as well?

> Do you know if anyone has successfully deployed VMs via KubeVirt in AWS EKS or EC2 without enabling emulation?

@karmab I think you would be able to answer this more accurately than I can since I don't have first hand experience here. I'll take a shot at answering this though. Please keep me honest

My understanding is that to run virtualization on an EC2 guest, the underlying instance type will need to be one of the metal instances.

https://aws.amazon.com/about-aws/whats-new/2019/02/introducing-five-new-amazon-ec2-bare-metal-instances/

> Side note: I'm fairly sure AWS doesn't support KVM on EC2 with the exception of "metal" instances, but I was hoping C5 (and maybe M5) would based on the EC2 FAQ:

While the C5/M5 instances are using the kvm hypervisor under the hood, it does not appear that nested virtualization is exposed to the C5's guest. Without nested virtualization support being passed into the guest you won't have kvm exposed in the guest, which means you're stuck with emulation.

If you have an AWS representative you're in contact with, you might want to inquire about the latest information on nested virtualization on C and M class ec2 instances. I know AWS is under pressure from the other providers to support nested virt, so there may be something they can tell you that isn't public knowledge yet (or is recent enough that I'm not aware of)

> Do you have any other ideas on why enabling emulation causes services (e.g. HAProxy) to fail to start in the VM? I initially assumed it was a network problem (and it might still be), but I also wonder if emulation mode is causing such a perf impact that services simply can't start in a reasonable amount of time.

Emulation mode isn't something we support for production workloads. It is only intended for demo purposes in environments where nested virtualization is not available. Our CI is not testing with emulation mode and there are no guarantees made about how it will behave. 

All that is to say... I don't know why HAProxy fails, but hearing that services work correctly with emulation disabled and fail with emulation enabled does not surprise me. The issue is most likely somehow related to how how the network device is passed into the KubeVirt guest vm. 

If you have any logs related to the HAProxy failure, this is something we might be able to provide more insight into if you are interested. 

Hopefully that helps answer some of your questions!

**Comment by fabiand** [comment]
All what David said, just some additions.

> * Do you know if anyone has successfully deployed VMs via KubeVirt in AWS EKS or EC2 without enabling emulation?

No.
And so far this was not a use-case for KubeVirt (to be run nested in the cloud).

> * Do you have any other ideas on why enabling emulation causes services (e.g. HAProxy) to fail to start in the VM? I initially assumed it was a network problem (and it might still be), but I also wonder if emulation mode is causing such a perf impact that services simply can't start in a reasonable amount of time.

Emulation will make the VM much slower, thus this can easily lead to timeouts and could trigger race conditions. Thus it's not a surprise that you are seeing these issues.

Today KubeVirt is targeted to be run on bare-metal nodes.
Today running KubeVirt in a nested environment is only used for CI purpose.
